site_name: Spacewalks Documentation
use_directory_urls: false
theme:
  name: "mkdocs"
  font: false
nav:
  - Spacewalks Documentation: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Background: explanation.md
  
plugins:
  - mkdocstrings